config/routes.rb
PlayListener::Application.routes.draw do
  devise_for :users, :path => "", :skip => [:sessions, :registration], :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  devise_scope :user do
    get    "login",  to: "users/sessions#new",     as: :login
    delete "logout", to: "users/sessions#destroy", as: :logout
  end

  resources :playlists, :only => [:index, :show] do
    post :synch, :on => :collection

    resources :tracks, :only => [:index] do
      post :synch, :on => :collection
    end
  end

  root :to => "home#index"
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  has_many   :tracks

  serialize :properties, ActiveRecord::Coders::Hstore

  %w[title summary description published_at].each do |key|
    define_method(key) do
      properties && properties[key]
    end

    define_method("#{key}=") do |value|
      self.properties = (properties || {}).merge(key => value)
    end
  end

  scope :by_uid, ->(uid) {where(:uid => uid)}

  def remote
    user.youtube.playlist(uid)
  end

  def synch_tracks
    if user.check_access_token!
      remote.videos.each do |video|
        track               = tracks.by_uid(video.unique_id).first || tracks.build
        track.uid           = video.unique_id if track.new_record?
        track.title         = video.title
        track.description   = video.description
        track.player_url    = video.player_url
        track.thumbnail_url = video.thumbnails.first.url
        track.published_at  = video.published_at
        track.duration      = video.duration
        track.save!
      end
    end
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :playlist

  serialize :properties, ActiveRecord::Coders::Hstore

  %w[title description published_at player_url thumbnail_url duration].each do |key|
    define_method(key) do
      properties && properties[key]
    end

    define_method("#{key}=") do |value|
      self.properties = (properties || {}).merge(key => value)
    end
  end

  scope :by_uid, ->(uid) {where(:uid => uid)}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :playlists

  devise :database_authenticatable, :encryptable, :omniauthable, :omniauth_providers => [:google_oauth2]

  serialize :properties, ActiveRecord::Coders::Hstore

  %w[yid username avatar_url].each do |key|
    define_method(key) do
      properties && properties[key]
    end

    define_method("#{key}=") do |value|
      self.properties = (properties || {}).merge(key => value)
    end
  end

  @youtube = nil

  scope :by_uid, ->(uid) {where(:uid => uid)}

  def self.find_for_google_oauth2(auth, signed_in_resource=nil)
    user = User.by_uid(auth.uid).first

    user = User.new unless user

    user.name          = auth.info.name
    user.email         = auth.info.email
    user.uid           = auth.uid
    user.access_token  = auth.credentials.token
    user.refresh_token = auth.credentials.refresh_token
    user.password      = Devise.friendly_token[10,20]

    begin
      profile = user.youtube.profile
    rescue
      profile = nil
    end

    if profile
      user.yid        = profile.user_id
      user.username   = profile.username_display
      user.avatar_url = profile.avatar
    end

    user.save!
    user
  end

  def youtube
    @youtube ||= YouTubeIt::OAuth2Client.new(
        client_access_token:  self.access_token,
        client_refresh_token: self.refresh_token,
        client_id:            GOOGLE_OAUTH2_CLIENT_ID,
        client_secret:        GOOGLE_OAUTH2_CLIENT_SECRET,
        dev_key:              GOOGLE_API_KEY
    )
  end

  def refresh_access_token!
    unless new_record?
      self.access_token = youtube.refresh_access_token!.token
      save!
    else
      false
    end
  end

  def check_access_token!
    if youtube.session_token_info[:code] == 200
      true
    else
      refresh_access_token!
    end
  end

  def synch_playlists
    if check_access_token!
      remote_playlists = youtube.playlists
      remote_playlists.each do |remote_playlist|
        playlist              = playlists.by_uid(remote_playlist.playlist_id).first || playlists.build
        playlist.uid          = remote_playlist.playlist_id if playlist.new_record?
        playlist.title        = remote_playlist.title
        playlist.summary      = remote_playlist.summary
        playlist.description  = remote_playlist.description
        playlist.published_at = remote_playlist.published
        playlist.save!
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to playlists_path if user_signed_in?
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_filter :authenticate_user!

  def synch
    current_user.synch_playlists

    redirect_to :back
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_filter :authenticate_user!
  before_filter :init_playlist

  def index
    @tracks = @playlist.tracks
  end

  def synch
    @playlist.synch_tracks
    redirect_to :back
  end

  private

  def init_playlist
    @playlist = current_user.playlists.find(params[:playlist_id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

    if user.persisted?
      sign_in_and_redirect(user, :event => :authentication)
    else
      redirect_to root_path
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new
    redirect_to user_omniauth_authorize_path(:google_oauth2)
  end

  def create
    super
  end

  def destroy
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title PlayListener
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}

    = stylesheet_link_tag("application", :media => "all")

    %link{:rel => "shortcut icon", :href => image_path("favicon.ico")}

    / HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file.
    /[if lt IE 9]
      = javascript_include_tag("flatui/html5shiv.js")

    = csrf_meta_tags
  %body
    .container
      = render "shared/header"
      = yield
      = render "shared/footer"
    / /.container

    = javascript_include_tag "application"

app/views/playlists/_breadcrumb.haml
%ul.breadcrumb
  %li.active
    = link_to "Playlists", playlists_path

app/views/playlists/_playlist.haml
%tr
  %td
    %span.fui-check
  %td= link_to playlist.title, playlist_tracks_path(playlist)
  %td #{time_ago_in_words(playlist.published_at)} ago
  %td
    = link_to playlist_tracks_path(playlist) do
      %span.fui-volume
      #{pluralize(playlist.tracks.count, "track")}
  %td
    = link_to synch_playlist_tracks_path(playlist), :class => "btn btn-inverse btn-small mll", :data => { :method => "post" } do
      = image_tag("icons/Magic@2x.png", :width => "20", :height => "20")
      %b &nbsp;Synch Tracks

app/views/playlists/index.haml
.dialog.dialog-success
  - if current_user.playlists.count == 0
    You still do not have active playlists. Maybe it's time to synchronize ;)
  - else
    You have synchronized #{pluralize(current_user.playlists.count, "playlist")}. Something has changed? Then try again :)

  = link_to synch_playlists_path, :class => "btn btn-inverse btn-wide mll", :data => { :method => "post" } do
    = image_tag("icons/Magic@2x.png", :width => "30", :height => "30")
    %b &nbsp;Synch Playlists
= render "breadcrumb"
%table.table.table-stripped
  %thead
    %tr
      %th
      %th Title
      %th Published
      %th
      %th
  %tbody
    = render current_user.playlists

app/views/shared/_footer.haml
.bottom-menu.bottom-menu-large.mbl
  .container
    .row
      .span2
      .span3.brand.pull-right
        %a.brand{:href => root_url, :title => "Play Listener"}
          = image_tag("icons/Key@2x.png", :width => "50", :height => "50")
          &copy #{Date.current.strftime("%Y")}

app/views/shared/_header.haml
%header
  .navbar
    .navbar-inner
      .container
        %button.btn.btn-navbar{:type => "button", :data => {:toggle => "collapse", :target => "#nav-collapse-01"}, :style => "position:relative;top:8px;"}
        %a.brand{ :href => root_url, :title => "Play Listener" }
          = image_tag("icons/Key@2x.png", :width => "50", :height => "50")
        .nav-collapse.collapse#nav-collapse-01
          %ul.nav.pull-right{:style => "position:relative;top:8px;"}
            - if user_signed_in?
              %li.hidden-desktop
                %a{ :href => "javascript:void(0);" }
                  - unless current_user.properties.empty?
                    %span.fui-user
                    = current_user.username
                  - else
                    %span.fui-alert
                    No linked YouTube account

              %li.dropdown.visible-desktop
                %a.dropdown-toggle{:href => "javascript:void(0);", :data => {:toggle => "dropdown"}}
                  %span.fui-user
                  %b.caret
                %ul.dropdown-menu
                  %li
                    %a{ :href => "javascript:void(0);" }
                      - unless current_user.properties.empty?
                        .thumbnail
                          = image_tag(current_user.avatar_url, :title => current_user.username, :alt => current_user.username, :class => "img-rounded")
                      - else
                        %span.fui-alert
                        No linked YouTube account

            %li.divider
            - if user_signed_in?
              %li
                = link_to logout_path, :data => { :method => :delete } do
                  %spam.fui-exit
                  Log Out
            - else
              %li
                = link_to login_path do
                  %span.fui-user
                  YouTube Log In

app/views/tracks/_breadcrumb.haml
%ul.breadcrumb
  %li
    = link_to "Playlists", playlists_path
  %li.active
    = link_to @playlist.title, playlist_tracks_path(@playlist)

app/views/tracks/_track.haml
%tr
  %td{:style => "vertical-align:middle;"}
    %span.fui-check
  %td
    %a{ :href => track.player_url }
      #{image_tag(track.thumbnail_url)}
  %td{:style => "vertical-align:middle;"}
    .row
      #{track.title}
    .row
      %br/
    .row
      %span.fui-export
      &nbsp;
      %a
        %span.label.label-inverse
          mp4
      %a
        %span.label.label-inverse
          m4a
      %a
        %span.label.label-inverse
          mp3
  %td{:style => "vertical-align:middle;"} #{Time.at(track.duration.to_i).gmtime.strftime('%R:%S')}
  %td{:style => "vertical-align:middle;"} #{time_ago_in_words(track.published_at)} ago

app/views/tracks/index.haml
.dialog.dialog-success
  - if @tracks.count == 0
    This playlist is empty. May be worth a try synchronize ;)
  - else
    You have synchronized #{pluralize(@tracks.count, "track")}. Is not it? Then try again :)

  = link_to synch_playlist_tracks_path(@playlist), :class => "btn btn-inverse btn-wide mll", :data => { :method => "post" } do
    = image_tag("icons/Magic@2x.png", :width => "30", :height => "30")
    %b &nbsp;Synch Tracks
= render "breadcrumb"
%table.table.table-stripped
  %thead
    %tr
      %th
      %th Original
      %th Title
      %th Duration
      %th Published
  %tbody
    = render @tracks